package polymod;

import haxe.Json;
import haxe.io.Bytes;
import polymod.backends.IBackend;
import polymod.backends.PolymodAssetLibrary;
import polymod.PolymodAssets;
import polymod.format.JsonHelp;
import polymod.format.ParseRules;
import polymod.fs.PolymodFileSystem;
import polymod.hscript._internal.Parser;
import polymod.hscript._internal.PolymodScriptClass;
import polymod.util.DependencyUtil;
import polymod.util.VersionUtil;
import thx.semver.Version;
import thx.semver.VersionRule;

using Lambda;
using StringTools;

#if firetongue
import firetongue.FireTongue;
#end

/**
 * The set of parameters which can be provided when initializing Polymod
 */
typedef PolymodParams =
{
  /**
   * (optional) The root directory for your game's mods.
   * On `SysFileSystem` (the default filesystem for desktop platforms), this parameter is required.
   */
  ?modRoot:String,

  /**
   * (optional) The mods that should be loaded, listed as their mod IDs.
   * If not provided, Polymod will initialize with no mods loaded.
   */
  ?modIds:Array<String>,

  /**
   * (optional) The mods that should be loaded, listed as their directory names relative to modRoot
   * If not provided, Polymod will initialize with no mods loaded.
   * DEPRECATED: Use `modIds` instead.
   */
  ?dirs:Array<String>,

  /**
   * (optional) The Haxe framework currently in use.
   * This is used to determine the proper backend injection methods to use.
   * If not provided, Polymod will attempt to determine this automatically.
   * Set to `CUSTOM` if you're using a custom backend.
   */
  ?framework:Framework,
  /**
   * (optional) Configuration specific to the framework currently in use.
   */
  ?frameworkParams:FrameworkParams,
  /**
   * (optional) Semantic Version rule of your game's modding API.
   * Provide a value as a string, like `"3.0.0"` or `"2.x"`.
   * If provided, Polymod will invalidate any mods whose versions are not compatible with this rule.
   */
  ?apiVersionRule:VersionRule,
  /**
   * (optional) A callback function which receives log and error messages generated by Polymod.
   * Check the `severity` to determine if the message is a notice or an error,
   * and use the `code` to determine the exact problem that occurred (and maybe provide a custom error or handling for it).
   */
  ?errorCallback:PolymodError->Void,
  /**
   * (optional) Parsing rules for various data formats.
   * Used to provide information on how to append and merge various data formats.
   * Defaults to `ParseRules.getDefault()`.
   */
  ?parseRules:ParseRules,
  /**
   * (optional) A list of filenames to ignore within mods.
   * By default, this will ignore license files, the mod metadata file, and mod icon file.
   */
  ?ignoredFiles:Array<String>,
  /**
   * (optional) Your own custom file backend for handling modded assets.
   * This can let you integrate Polymod with a game engine which normally isn't supported.
   * Set the `framework` parameter to `CUSTOM` and provide a class implementing `IBackend`.
   */
  ?customBackend:Class<IBackend>,
  /**
   * (optional) A map associating different file extensions with different file types.
   * This tells Polymod to handle certain assets as text, certain assets as images, etc.
   */
  ?extensionMap:Map<String, PolymodAssetType>,
  /**
   * (optional) Your own custom backend for accessing the file system.
   *
   * By default, Polymod will load mods from your local native filesystem.
   * This parameter lets you provide your own filesystem implementation.
   * This is important if you want to support HTML5, or load mods from a remote server, or something custom.
   * You can either write your own filesystem, or use one of the ones provided in the `polymod.fs` package.
   *
   * This parameter takes either an instance of `IFileSystem` or a `Class<T>` implementing `IFileSystem`.
   */
  ?customFilesystem:Dynamic,
  /**
   * (optional) A set of parameters for initializing the filesystem.
   * Some filesystems may ignore some of these parameters.
   */
  ?fileSystemParams:PolymodFileSystemParams,
  /**
   * (optional) Specify the name of your assets folder.
   * Defaults to `assets/`; if your assets folder is not named `assets/`, you can specify the correct name here.
   * This prevents some bugs when calling `Assets.list()`, among other things.
   */
  ?assetPrefix:String,
  /**
   * (optional) Disables dependency checks. Defaults to `false`.
   * By default, Polymod will query all the loaded mods, and either exclude mods whose dependencies are not met,
   * or reorganize the load order to ensure that mods are loaded after their dependencies.
   *
   * Setting this to `true` will disable this behavior entirely.
   * Mods will be loaded in the order they are provided.
   *
   * This is NOT recommended as issues may result from loading mods in the wrong order,
   * or while loading a mod with a missing dependency.
   */
  ?skipDependencyChecks:Bool,
  /**
   * (optional) If `false`, Polymod will completely stop loading mods if any mods have missing dependencies.
   * If `true`, Polymod will skip loading mods that have missing dependencies, but will continue loading other mods.
   *
   * Defaults to `false`.
   */
  ?skipDependencyErrors:Bool,

  /**
   * (optional) A FireTongue instance for Polymod to hook into.
   * This is used for robust support for asset localization
   */
  #if firetongue
  ?firetongue:FireTongue,
  #end
  /**
   * (optional) Whether to perform the required initialization for scripted classes.
   *
   * Defaults to `false`.
   */
  ?useScriptedClasses:Bool,

  /**
   * (optional) If `useScriptedClasses` is true, perform script loading asynchronously.
   *
   * Defaults to `false`.
   */
  ?loadScriptsAsync:Bool,
}

/**
 * Any framework-specific settings
 * Right now this is only used to specify asset library paths for the Lime/OpenFL framework, but we'll add more framework-specific settings here as needed
 */
typedef FrameworkParams =
{
  /**
   * (optional) if you're using Lime/OpenFL AND you're using custom or non-default asset libraries, then you must provide a key=>value store mapping the name of each asset library to a path prefix in your mod structure
   */
  ?assetLibraryPaths:Map<String, String>,

  /**
   * (optional) specify this path to redirect core asset loading to a different path
   * you can set this up to load core assets from a parent directory!
   * Not applicable for file systems which don't use a directory obvs.
   */
  ?coreAssetRedirect:String
}

typedef ScanParams =
{
  ?modRoot:String,
  ?apiVersionRule:VersionRule,
  ?errorCallback:PolymodError->Void,
  ?fileSystem:IFileSystem
}

/**
 * The framework which your Haxe project is using to manage assets
 */
enum Framework
{
  CASTLE;
  NME;
  LIME;
  OPENFL;
  OPENFL_WITH_NODE;
  FLIXEL;
  HEAPS;
  KHA;
  CERAMIC;
  CUSTOM;
  UNKNOWN;
}

/**
 * A system for modifying the behavior of existing asset frameworks,
 * for the creation of atomic modding systems for your game.
 */
@:allow(polymod.hscript._internal.PolymodScriptClass)
@:allow(polymod.PolymodAssets)
class Polymod
{
  /**
   * The callback function for any errors or notices generated by Polymod.
   * Populate this by calling `init({errorCallback = myCallback})`.
   */
  public static var onError:Null<PolymodError->Void> = null;

  /**
   * The internal asset library used by Polymod.
   */
  static var assetLibrary:PolymodAssetLibrary = null;

  #if firetongue
  /**
   * A FireTongue instance for Polymod to hook into for asset localization support.
   */
  static var tongue:FireTongue = null;
  #end

  /**
   * The PolymodParams used when `init()` was last called.
   */
  static var prevParams:PolymodParams = null;

  /**
   * The mods loaded when `init()` was last called.
   * Useful for removing old mods from the preprocessor map.
   */
  static var prevModsLoaded:Array<ModMetadata> = [];

  /**
   * Initializes Polymod, while loading the chosen mod or mods.
   *
   * @param params A set of parameters to use when initializing Polymod.
   * @return An array of metadata entries for the mods which were successfully loaded.
   */
  public static function init(params:PolymodParams):Array<ModMetadata>
  {
    if (params.errorCallback != null) onError = params.errorCallback;

    var modRoot = params.modRoot;
    if (modRoot == null)
    {
      if (params.fileSystemParams.modRoot != null)
      {
        modRoot = params.fileSystemParams.modRoot;
      }
      else
      {
        modRoot = './mods';
      }
    }

    params.modIds ??= [];
    params.dirs ??= [];

    if (params.fileSystemParams == null) params.fileSystemParams = {modRoot: modRoot};
    if (params.fileSystemParams.modRoot == null) params.fileSystemParams.modRoot = modRoot;
    if (params.apiVersionRule == null) params.apiVersionRule = VersionUtil.DEFAULT_VERSION_RULE;
    var fileSystem = PolymodFileSystem.makeFileSystem(params.customFilesystem, params.fileSystemParams);

    // Fetch mod metadata and exclude broken mods.
    var modsToLoad:Array<ModMetadata> = [];

    if (params.modIds.length > 0)
    {
      for (i in 0...params.modIds.length)
      {
        var modId:Null<String> = params.modIds[i];
        if (modId == null) continue;
        var meta:ModMetadata = fileSystem.getMetadataById(modId);

        if (meta != null)
        {
          if (!VersionUtil.match(meta.apiVersion, params.apiVersionRule))
          {
            error(MOD_API_VERSION_MISMATCH,
              'Mod "${modId}" was built for incompatible API version ${meta.apiVersion.toString()}, expected "${params.apiVersionRule.toString()}"', INIT);
          }

          // API version matches
          modsToLoad.push(meta);
        }
      }
    }
    else if (params.dirs.length > 0)
    {
      for (i in 0...params.dirs.length)
      {
        var modDir:Null<String> = params.dirs[i];
        var meta:ModMetadata = fileSystem.getMetadataByDir(modDir);

        if (meta != null)
        {
          if (!VersionUtil.match(meta.apiVersion, params.apiVersionRule))
          {
            error(MOD_API_VERSION_MISMATCH,
              'Mod "${modDir}" was built for incompatible API version ${meta.apiVersion.toString()}, expected "${params.apiVersionRule.toString()}"', INIT);
          }

          // API version matches
          modsToLoad.push(meta);
        }
      }
    }

    // Sort mods by dependencies.
    var sortedModsToLoad:Array<ModMetadata> = modsToLoad;

    if (!params.skipDependencyChecks)
    {
      sortedModsToLoad = DependencyUtil.sortByDependencies(modsToLoad, params.skipDependencyErrors);
      sortedModsToLoad ??= [];
    }
    else
    {
      Polymod.warning(MOD_DEPENDENCY_CHECK_SKIPPED, "Dependency checks were skipped.", INIT);
    }

    // Get the file path for each mod to load, in order.
    var sortedModIds:Array<String> = sortedModsToLoad.map(function(meta:ModMetadata):String {
      return meta.id;
    });
    var sortedModPaths:Array<String> = sortedModsToLoad.map(function(meta:ModMetadata):String {
      return meta.modPath;
    });

    assetLibrary = PolymodAssetLibrary.build(
      {
        framework: params.framework,
        modIds: sortedModIds,
        modDirs: sortedModPaths,
        parseRules: params.parseRules,
        ignoredFiles: params.ignoredFiles,
        customBackend: params.customBackend,
        extensionMap: params.extensionMap,
        frameworkParams: params.frameworkParams,
        fileSystem: fileSystem,
        assetPrefix: params.assetPrefix,
        #if firetongue
        firetongue: params.firetongue,
        #end
      });

    if (assetLibrary == null)
    {
      // Polymod failed to initialize.
      return null;
    }

    // If we're here... Polymod initialized successfully!
    // Time for some post-initialization cleanup.

    // Store the params for later use (by loadMod, unloadMod, and clearMods)
    prevParams = params;

    // Do scripted class initialization now that the assetLibrary is loaded.
    if (params.useScriptedClasses)
    {
      Polymod.info(SCRIPT_PARSE_START, 'Parsing script classes...');
      Polymod.clearScripts();

      // Add the loaded mods to the Parser's preprocessor values.
      for (mod in prevModsLoaded)
      {
        Parser.preprocessorValues.remove(mod.id);
      }

      for (mod in sortedModsToLoad)
      {
        Parser.preprocessorValues.set(mod.id, mod.modVersion.toString());
      }

      if (params.loadScriptsAsync)
      {
        #if lime
        Polymod.registerAllScriptClassesAsync();
        #else
        Polymod.error(BACKEND_INIT_FAILED, 'The current backend does not support asynchronous script loading!', INIT);
        #end
      }
      else
      {
        Polymod.registerAllScriptClasses();

        var classList = polymod.hscript._internal.PolymodScriptClass.listScriptClasses();
        Polymod.info(SCRIPT_PARSE_DONE, 'Parsed and registered ${classList.length} scripted classes.');
      }
    }

    // Store the mods for the later `init()` calls.
    prevModsLoaded = sortedModsToLoad.copy();

    return sortedModsToLoad;
  }

  public static function getLoadedModDirs():Array<String>
  {
    return assetLibrary.modDirs;
  }

  /**
   * Retrieve the IFileSystem instance currently in use by Polymod.
   * This may be useful if you're using a MemoryFileSystem or a custom file system that you want to call functions on.
   */
  public static function getFileSystem():Null<IFileSystem>
  {
    if (assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot return file system.', INIT);
      return null;
    }
    return assetLibrary.fileSystem;
  }

  /**
   * Reinitializes Polymod (with the same parameters) while additionally enabling an individual mod.
   * The new mod will get added to the end of the modlist (unless mod dependencies require otherwise).
   *
   * Depending on the framework you are using, especially if you loaded a specific file already,
   * you may have to call `clearCache()` for this to take effect.
   *
   * @param modId The ID of the mod to load.
   * @return A list of all mods that were successfully loaded.
   */
  public static function loadMod(modId:String):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mod "$modId".', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Add the mod to the list of mods to load.
    newParams.modIds = newParams.modIds.concat([modId]);
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while additionally enabling an individual mod.
   * The new mod will get added to the end of the modlist (unless mod dependencies require otherwise).
   *
   * Depending on the framework you are using, especially if you loaded a specific file already,
   * you may have to call `clearCache()` for this to take effect.
   *
   * @param modDir The directory of the mods to load.
   * @return A list of all mods that were successfully loaded.
   */
  public static function loadModByDir(modDir:String):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mod "$modDir".', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Add the mod to the list of mods to load.
    newParams.dirs = newParams.dirs.concat([modDir]);
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while additionally enabling several mods.
   * The new mods will get added to the end of the modlist (unless mod dependencies require otherwise).
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   *
   * @param modIds The IDs of the mods to load.
   * @return A list of all mods that were successfully loaded.
   */
  public static function loadMods(modIds:Array<String>):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mods $modIds.', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Add the mods to the list of mods to load.
    newParams.modIds = newParams.modIds.concat(modIds);
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while additionally enabling several mods.
   * The new mods will get added to the end of the modlist (unless mod dependencies require otherwise).
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   *
   * @param modDirs The directories of the mods to load.
   * @return A list of all mods that were successfully loaded.
   */
  public static function loadModsByDir(modDirs:Array<String>):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mods $modDirs.', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Add the mods to the list of mods to load.
    newParams.dirs = newParams.dirs.concat(modDirs);
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while enabling a list of mods.
   * The new modlist will replace the old modlist.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   *
   * @param modIds The IDs of the mods to load.
   * @return A list of all mods that were successfully loaded.
   */
  public static function loadOnlyMods(modIds:Array<String>):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mods $modIds.', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Set the list of mods to load.
    newParams.modIds = modIds;
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while enabling a list of mods.
   * The new modlist will replace the old modlist.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   *
   * @param modDirs The directories of the mods to load.
   * @return A list of all mods that were successfully loaded.
   */
  public static function loadOnlyModsByDir(modDirs:Array<String>):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mods $modDirs.', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Set the list of mods to load.
    newParams.dirs = modDirs;
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod, with the same parameters.
   * Useful to force Polymod to detect newly added files.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already,
   * you may have to call `clearCache()` for this to take effect.
   *
   * @return A list of all mods that were successfully loaded.
   */
  public static function reload():Array<ModMetadata>
  {
    var newParams = Reflect.copy(prevParams);
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;
    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while additionally disabling an individual mod.
   * The specified mod will get removed from the modlist.
   * If the unloaded mod was a dependency, depending on your configuration,
   * either dependent mods will also be disabled, or Polymod will throw an error and unload nothing.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   *
   * @return A list of all mods that were successfully loaded.
   */
  public static function unloadMod(dir:String):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mod "$dir".', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Add the mod to the list of mods to load.
    newParams.dirs.remove(dir);
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while additionally disabling several mods.
   * The specified mods will get removed from the modlist.
   * If the unloaded mods were dependencies, depending on your configuration,
   * either dependent mods will also be disabled, or Polymod will throw an error and unload nothing.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   *
   * @return A list of all mods that were successfully loaded.
   */
  public static function unloadMods(modDirs:Array<String>):Array<ModMetadata>
  {
    // Check if Polymod is loaded.
    if (prevParams == null || assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot load mod "$modDirs".', INIT);
      return [];
    }

    var newParams = Reflect.copy(prevParams);
    // Add the mod to the list of mods to load.
    for (dir in modDirs)
    {
      newParams.dirs.remove(dir);
    }
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    return Polymod.init(newParams);
  }

  /**
   * Reinitializes Polymod (with the same parameters) while turning off all mods.
   * If you are using Firetongue integration, localized asset replacements will still apply.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   */
  public static function unloadAllMods():Void
  {
    // Check if Polymod is loaded.
    if (assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot clear mods.', INIT);
      return;
    }

    var newParams = Reflect.copy(prevParams);
    // Clear the modlist.
    newParams.dirs = [];
    // Keep the same file system between reloads.
    newParams.customFilesystem = assetLibrary.fileSystem;

    Polymod.init(newParams);
  }

  /**
   * Fully disables Polymod and disables any asset replacements, from mods or from locales.
   *
   * Depending on the framework you are using, especially if you loaded a specific file already.
   * you may have to call `clearCache()` for this to take effect.
   */
  public static function disable():Void
  {
    // Check if Polymod is loaded.
    if (assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot clear mods.', INIT);
      return;
    }

    assetLibrary.destroy();
    assetLibrary = null;
  }

  /**
   * Builds the list of files which Polymod will ignore, by default, when loading mods.
   * Includes license files and metadata files.
   *
   * @return A list of filenames.
   */
  public static function getDefaultIgnoreList():Array<String>
  {
    return PolymodConfig.modIgnoreFiles.concat([PolymodConfig.modMetadataFile, PolymodConfig.modIconFile]);
  }

  /**
   * Scan the given directory for available mods and returns their metadata entries.
   * Note that if Polymod is already initialized, all parameters are ignored and optional.
   *
   * @param modRoot (optional) root directory of all mods. Optional if Polymod is initialized.
   * @param apiVersionRule (optional) enforce a modding API version rule -- incompatible mods will not be returned
   * @param errorCallback (optional) callback for any errors generated during scanning
   * @return Array<ModMetadata>
   */
  public static function scan(?scanParams:ScanParams):Array<ModMetadata>
  {
    if (scanParams == null)
    {
      // Scan using assetLibrary's file system.
      if (assetLibrary == null)
      {
        Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot scan for mods.', INIT);
        return [];
      }

      return assetLibrary.fileSystem.scanMods(prevParams.apiVersionRule);
    }
    else
    {
      // Scan using the provided parameters.
      if (scanParams.modRoot == null) scanParams.modRoot = './mods';

      if (scanParams.apiVersionRule == null) scanParams.apiVersionRule = VersionUtil.DEFAULT_VERSION_RULE;

      if (scanParams.fileSystem == null)
      {
        if (assetLibrary != null)
        {
          scanParams.fileSystem = assetLibrary.fileSystem;
        }
        else
        {
          scanParams.fileSystem = PolymodFileSystem.makeFileSystem(null, {modRoot: scanParams.modRoot});
        }
      }

      return scanParams.fileSystem.scanMods(scanParams.apiVersionRule);
    }
  }

  /**
   * Re-sort the list of mods such that dependency order is satisfied.
   *
   * @param modMetadatas The list of mods to reorder.
   * @param strict If `true`, return `[]` if a required dependency is unmet.
   * @return The sorted list.
   */
  public static function sortModsByDependencies(modMetadatas:Array<ModMetadata>, strict:Bool = false):Array<ModMetadata>
  {
    return DependencyUtil.sortByDependencies(modMetadatas, !strict);
  }

  /**
   * Determines whether all mandatory dependencies are met for each mod in the list.
   *
   * @param modMetadatas The list of mods to validate.
   * @return Whether all required, non-optional dependencies are met.
   */
  public static function validateModDependencies(modMetadatas:Array<ModMetadata>):Bool
  {
    return DependencyUtil.validateDependencies(modMetadatas);
  }

  /**
   * Tells Polymod to force the current backend to clear any asset caches.
   */
  public static function clearCache():Void
  {
    if (assetLibrary == null)
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot clear cache.', INIT);
      return;
    }

    Polymod.debug('Clearing backend asset cache...');
    assetLibrary.clearCache();
  }

  /**
   * Clears all scripted functions and any registered scripted classes from the cache.
   * This is useful if you want to reload the scripts later.
   */
  public static function clearScripts():Void
  {
    @:privateAccess
    polymod.hscript._internal.PolymodScriptClass.clearScriptedClasses();
    polymod.hscript._internal.PolymodEnum.clearScriptedEnums();
    #if hscript_typer
    polymod.hscript._internal.PolymodTyperEx.clearAllModules();
    #end
    polymod.hscript.HScriptable.ScriptRunner.clearScripts();
  }

  /**
   * Get a list of all the available scripted classes (`.hxc` files), interpret them, and register any classes.
   */
  public static function registerAllScriptClasses():Void
  {
    @:privateAccess {
      // Go through each script and parse any classes in them.
      var potentialScripts:Array<String> = Polymod.assetLibrary.list(TEXT);
      var libraryIds:Array<String> = Polymod.assetLibrary.listLibraries();

      for (textPath in potentialScripts)
      {
        if (PolymodConfig.scriptClassExt.exists(ext -> textPath.endsWith(ext)))
        {
          var path = textPath;
          if (!Polymod.assetLibrary.exists(path))
          {
            for (libraryId in libraryIds)
            {
              if (Polymod.assetLibrary.exists('$libraryId:$textPath'))
              {
                path = '$libraryId:$textPath';
                break;
              }
            }
            if (!Polymod.assetLibrary.exists(path)) throw 'Couldn\'t find file "$textPath"';
          }
          Polymod.debug('Registering scripted class "$path"');
          polymod.hscript._internal.PolymodScriptClass.registerScriptClassByPath(path);
        }
      }

      #if hscript_typer
      // in the future typed modules might have a use
      // but for now we just ignore the typed modules that are returned
      var _ = polymod.hscript._internal.PolymodTyperEx.typeAllModules();
      #end

      polymod.hscript._internal.Interp.validateImports();
    }
  }

  /**
   * Get a list of all the available scripted classes (`.hxc` files), interpret them asynchronously, and register any classes.
   * Called on platforms that don't support synchronous file access.
   */
  #if lime
  public static function registerAllScriptClassesAsync():Array<lime.app.Future<Bool>>
  {
    // Go through each script and parse any classes in them.
    var potentialScripts:Array<String> = Polymod.assetLibrary.list(TEXT);
    var libraryIds:Array<String> = Polymod.assetLibrary.listLibraries();

    var futures:Array<lime.app.Future<Bool>> = [];
    for (textPath in potentialScripts)
    {
      if (PolymodConfig.scriptClassExt.exists(ext -> textPath.endsWith(ext)))
      {
        var path = textPath;
        if (!Polymod.assetLibrary.exists(path))
        {
          for (libraryId in libraryIds)
          {
            if (Polymod.assetLibrary.exists('$libraryId:$textPath'))
            {
              path = '$libraryId:$textPath';
              break;
            }
          }
          if (!Polymod.assetLibrary.exists(path)) throw 'Couldn\'t find file "$textPath" (tried libraries ${libraryIds})';
        }
        Polymod.debug('Fetching scripted class "$path"');
        var future = polymod.hscript._internal.PolymodScriptClass.registerScriptClassByPathAsync(path);
        if (future != null) futures.push(future);
      }
    }

    polymod.hscript._internal.Interp.validateImports();

    return futures;
  }
  #end

  /**
   * Dispatch an error message with the severity `PolymodErrorType.ERROR`.
   * Use this for severe errors that the user should be notified about.
   * @param code The error code.
   * @param message The message to display.
   * @param origin The context the error occurred in (while scanning for mods, while initializing mods, etc).
   */
  public static function error(code:PolymodErrorCode, message:String, origin:PolymodErrorOrigin = UNKNOWN):Void
  {
    if (onError != null)
    {
      onError(new PolymodError(PolymodErrorType.ERROR, code, message, origin));
    }
  }

  /**
   * Dispatch an error message with the severity `PolymodErrorType.WARNING`.
   * Use this for issues that the user might want to know about.
   * @param code The error code.
   * @param message The message to display.
   * @param origin The context the error occurred in (while scanning for mods, while initializing mods, etc).
   */
  public static function warning(code:PolymodErrorCode, message:String, origin:PolymodErrorOrigin = UNKNOWN):Void
  {
    if (onError != null)
    {
      onError(new PolymodError(PolymodErrorType.WARNING, code, message, origin));
    }
  }

  /**
   * Dispatch an error message with the severity `PolymodErrorType.INFO`.
   * Use this for information developers would likely want to know about.
   * @param code The error code.
   * @param message The message to display.
   * @param origin The context the error occurred in (while scanning for mods, while initializing mods, etc).
   */
  public static function info(code:PolymodErrorCode, message:String, origin:PolymodErrorOrigin = UNKNOWN):Void
  {
    if (onError != null)
    {
      onError(new PolymodError(PolymodErrorType.INFO, code, message, origin));
    }
  }

  /**
   * Dispatch an error message with the severity `PolymodErrorType.DEBUG`.
   * Debug messages are only dispatched if `PolymodConfig.debug` is `true`, and have no error code.
   * @param message The message to display.
   * @param posInfo The position the function was called from.
   */
  public static function debug(message:String, ?posInfo:haxe.PosInfos):Void
  {
    if (onError != null && PolymodConfig.debug)
    {
      onError(new PolymodError(PolymodErrorType.DEBUG, null, message, UNKNOWN));
    }
  }

  /**
   * Provide a list of assets included in or modified by the mod(s)
   * @param type the type of asset you want (lime.utils.PolymodAssetType)
   * @return Array<String> a list of assets of the matching type
   */
  public static function listModFiles(?type:PolymodAssetType):Array<String>
  {
    if (assetLibrary != null)
    {
      return assetLibrary.listModFiles(type);
    }
    else
    {
      Polymod.warning(POLYMOD_NOT_INITIALIZED, 'Polymod is not loaded yet, cannot list files.', INIT);
      return [];
    }
  }

  /**
   * When a scripted class defines an import, you can define another class which should be imported instead.
   * @param importAlias The full import path to use as an alias, as a string.
   * @param importClass The class type to import instead.
   */
  public static function addImportAlias(importAlias:String, importClass:Class<Dynamic>):Void
  {
    PolymodScriptClass.importOverrides.set(importAlias, importClass);
  }

  /**
   * Remove an import alias previously defined by `addImportAlias()`.
   * @param importAlias The full import class to use as an alias, to be removed.
   */
  public static function removeImportAlias(importAlias:String):Void
  {
    PolymodScriptClass.importOverrides.remove(importAlias);
  }

  /**
   * Define a class to be imported by default in all scripted classes.
   * @param importClass The class type to import.
   * @param importAlias (optional) The alias to use for the import. If not provided, the full class path will be used.
   */
  public static function addDefaultImport(importClass:Class<Dynamic>, ?importAlias:String):Void
  {
    PolymodScriptClass.defaultImports.set(importAlias == null ? Type.getClassName(importClass) : importAlias, importClass);
  }

  /**
   * When a scripted class define an import, you can blacklist it from being imported.
   * @param importPath The full import path to blacklist, as a string.
   */
  public static function blacklistImport(importPath:String):Void
  {
    addImportAlias(importPath, null);
  }

  /**
   * When a static field is being called, you can blacklist it from being used.
   * @param parentClass The class type with the fields.
   * @param fields The static fields you want to blacklist.
   */
  public static function blacklistStaticFields(parentClass:Class<Dynamic>, fields:Array<String>):Void
  {
    PolymodScriptClass.blacklistedStaticFields.set(parentClass, fields);
  }

  /**
   * When an instance field is being called, you can blacklist it from being used.
   * @param parentClass The class type with the fields.
   * @param fields The instance fields you want to blacklist.
   */
  public static function blacklistInstanceFields(parentClass:Class<Dynamic>, fields:Array<String>):Void
  {
    PolymodScriptClass.blacklistedInstanceFields.set(Type.getClassName(parentClass), fields);
  }
}

/**
 * A type representing a contributor to a mod.
 * Allows for providing an optional role and contact information.
 */
typedef ModContributor =
{
  name:String,
  ?role:String,
  ?email:String,
  ?url:String
};

/**
 * A type representing a mod's dependencies.
 *
 * The map takes the mod's ID as the key and the required version as the value.
 * The version follows the Semantic Versioning format, with `*.*.*` meaning any version.
 */
typedef ModDependencies = Map<String, VersionRule>;

/**
 * A type representing data about a mod, as retrieved from its metadata file.
 */
class ModMetadata
{
  /**
   * The internal ID of the mod.
   */
  public var id:String;

  /**
   * The human-readable name of the mod.
   */
  public var title:String;

  /**
   * A short description of the mod.
   */
  public var description:String;

  /**
   * A link to the homepage for a mod.
   * Should provide a URL where the mod can be downloaded from.
   */
  public var homepage:String;

  /**
   * A version number for the API used by the mod.
   * Used to prevent compatibility issues with mods when the application changes.
   */
  public var apiVersion:Version;

  /**
   * A version number for the mod itself.
   * Should be provided in the Semantic Versioning format.
   */
  public var modVersion:Version;

  /**
   * The name of a license determining the terms of use for the mod.
   */
  public var license:String;

  /**
   * Binary data containing information on the mod's icon file, if it exists.
   * This is useful when you want to display the mod's icon in your application's mod menu.
   */
  public var icon:Bytes = null;

  /**
   * The path on the filesystem to the mod's icon file.
   */
  public var iconPath:String;

  /**
   * The path where this mod's files are stored, on the IFileSystem.
   */
  public var modPath:String;

  /**
   * The directory name of the mod.
   */
  public var dirName:String;

  /**
   * `metadata` provides an optional list of keys.
   * These can provide additional information about the mod, specific to your application.
   */
  public var metadata:Map<String, String>;

  /**
   * A list of dependencies.
   * These other mods must be also be loaded in order for this mod to load,
   * and this mod must be loaded after the dependencies.
   */
  public var dependencies:ModDependencies;

  /**
   * A list of dependencies.
   * This mod must be loaded after the optional dependencies,
   * but those mods do not necessarily need to be loaded.
   */
  public var optionalDependencies:ModDependencies;

  /**
   * A deprecated field representing the mod's author.
   * Please use the `contributors` field instead.
   */
  @:deprecated
  public var author(get, set):String;

  // author has been made a property so setting it internally doesn't throw deprecation warnings
  var _author:String;

  function get_author()
  {
    if (contributors.length > 0)
    {
      return contributors[0].name;
    }
    return _author;
  }

  function set_author(v):String
  {
    if (contributors.length == 0)
    {
      contributors.push({name: v});
    }
    else
    {
      contributors[0].name = v;
    }
    return v;
  }

  /**
   * A list of contributors to the mod.
   * Provides data about their roles as well as optional contact information.
   */
  public var contributors:Array<ModContributor>;

  public function new()
  {
    // No-op constructor.
  }

  /**
   * Converts a ModMetadata object to a JSON string.
   * @return The JSON string.
   */
  public function toJsonStr():String
  {
    var json = {};
    Reflect.setField(json, 'title', title);
    Reflect.setField(json, 'description', description);
    // Reflect.setField(json, 'author', _author);
    Reflect.setField(json, 'contributors', contributors);
    Reflect.setField(json, 'homepage', homepage);
    Reflect.setField(json, 'api_version', apiVersion.toString());
    Reflect.setField(json, 'mod_version', modVersion.toString());
    Reflect.setField(json, 'license', license);
    var meta = {};
    for (key in metadata.keys())
    {
      Reflect.setField(meta, key, metadata.get(key));
    }
    Reflect.setField(json, 'metadata', meta);
    return Json.stringify(json, null, '    ');
  }

  /**
   * Constructs a ModMetadata object from a JSON string.
   * @param str The JSON string.
   * @param origin The context we are calling this from (for error reporting).
   * @return The ModMetadata object, or `null` if it could not be loaded.
   */
  public static function fromJsonStr(str:String, ?origin:PolymodErrorOrigin):Null<ModMetadata>
  {
    if (str == null || str == '')
    {
      Polymod.error(MOD_METADATA_PARSE_FAILED, 'Error parsing mod metadata file: Contents were null or empty.', origin);
      return null;
    }

    var json = null;
    try
    {
      json = haxe.Json.parse(str);
    }
    catch (msg:Dynamic)
    {
      Polymod.error(MOD_METADATA_PARSE_FAILED, 'Error parsing mod metadata file: (${msg})', origin);
      return null;
    }

    var m = new ModMetadata();
    m.id = JsonHelp.str(json, 'id');
    m.title = JsonHelp.str(json, 'title');
    m.description = JsonHelp.str(json, 'description');
    m._author = JsonHelp.str(json, 'author');
    m.contributors = JsonHelp.arrType(json, 'contributors');
    m.homepage = JsonHelp.str(json, 'homepage');
    var apiVersionStr = JsonHelp.str(json, 'api_version');
    var modVersionStr = JsonHelp.str(json, 'mod_version');
    try
    {
      m.apiVersion = apiVersionStr;
    }
    catch (msg:Dynamic)
    {
      Polymod.error(MOD_API_VERSION_PARSE_FAILED, 'Error parsing API version from metadata: ${msg}', origin);
      return null;
    }
    try
    {
      m.modVersion = modVersionStr;
    }
    catch (msg:Dynamic)
    {
      Polymod.error(MOD_VERSION_PARSE_FAILED, 'Error parsing mod version from metadata: ${msg}', origin);
      return null;
    }
    m.license = JsonHelp.str(json, 'license');
    m.metadata = JsonHelp.mapStr(json, 'metadata');

    m.dependencies = JsonHelp.mapVersionRule(json, 'dependencies');
    m.optionalDependencies = JsonHelp.mapVersionRule(json, 'optionalDependencies');

    return m;
  }

  public function toString():String
  {
    return 'ModMetadata($id:$modVersion)';
  }
}

/**
 * Structured data on an error that occurred during Polymod's operation.
 */
class PolymodError
{
  /**
   * Indicates the severity of the issue.
   * See `PolymodErrorType` for more information.
   */
  public var severity:PolymodErrorType;

  /**
   * A particular error which occurred during Polymod's operation.
   * You can use this with a switch statement to automatically resolve specific errors,
   * or provide special messages for others.
   */
  public var code:PolymodErrorCode;

  /**
   * A human-readable message providing more context for the error which occurred.
   */
  public var message:String;

  /**
   * Some brief context on where the error occurred.
   */
  public var origin:PolymodErrorOrigin;

  public function new(severity:PolymodErrorType, code:PolymodErrorCode, message:String, ?origin:PolymodErrorOrigin = UNKNOWN)
  {
    this.severity = severity;
    this.code = code;
    this.message = message;
    this.origin = origin;
  }
}

/**
 * Indicates where the error occurred.
 */
enum abstract PolymodErrorOrigin(String) from String to String
{
  /**
   * This error occurred while scanning for mods.
   */
  public var SCAN:String = 'scan';

  /**
   * This error occurred while initializing Polymod.
   */
  public var INIT:String = 'init';

  /**
   * This error occurred before or during the execution of a script.
   */
  public var SCRIPT_RUNTIME:String = 'script_runtime';

  /**
   * This error occurred in an undefined location.
   */
  public var UNKNOWN:String = 'unknown';
}

/**
 * Represents the severity level of a given message.
 */
enum PolymodErrorType
{
  /**
   * This message is merely an informational notice.
   * You can simply ignore it.
   */
  DEBUG;

  /**
   * This message is merely an informational notice.
   * You can handle it with a popup, log it, or simply ignore it.
   */
  INFO;

  /**
   * This message is a warning.
   * Either the application developer, the mod developer, or the user did something wrong.
   */
  WARNING;

  /**
   * This message indicates a severe error occurred.
   * This almost certainly will cause unintended behavior. A certain mod may not load or may even cause crashes.
   */
  ERROR;
}

/**
 * Represents the particular type of error that occurred.
 * Great to use as the condition of a switch statement to provide special handling for specific errors.
 */
enum abstract PolymodErrorCode(String) from String to String
{
  //
  // General Errors
  //

  /**
   * You attempted to use a functionality of Polymod that is not fully implemented, or not implemented for the current framework.
   * - Report the issue here, and describe your setup and provide the error message:
   *   https://github.com/FunkinCrew/Polymod/issues
   */
  public var POLYMOD_FUNCTIONALITY_NOT_IMPLEMENTED:String = 'polymod_functionality_not_implemented';

  /**
   * You attempted to use a functionality of Polymod that has been deprecated and has/will be significantly reworked or altered.
   * - New features and their associated documentation will be provided in future updates.
   */
  public var POLYMOD_FUNCTIONALITY_DEPRECATED:String = 'polymod_functionality_deprecated';

  /**
   * The app attempted to use a functionality of Polymod that requires Polymod to be initialized,
   * but Polymod has not been initialized yet.
   * - Make sure you call `Polymod.init()` before attempting to call this function.
   */
  public var POLYMOD_NOT_INITIALIZED:String = 'app_polymod_not_initialized';

  //
  // Mod Metadata Parsing Errors
  //

  /**
   * You requested a mod to be loaded but that mod was not installed.
   * - Make sure a mod with that directory is installed.
   * - Make sure to run Polymod.scan() to get the list of valid mod directories.
   */
  public var MOD_MISSING_DIRECTORY:String = 'mod_missing_directory';

  /**
   * You requested a mod to be loaded but that mod was not installed.
   * - Make sure a mod with that ID is installed.
   */
  public var MOD_MISSING_ID:String = 'mod_missing_id';

  /**
   * You requested a mod to be loaded but its mod folder is missing a metadata file.
   * - Make sure the mod folder contains a metadata JSON file. Polymod won't recognize the mod without it.
   */
  public var MOD_MISSING_METADATA:String = 'mod_missing_metadata';

  /**
   * The mod's metadata file could not be parsed.
   * - Make sure the file contains valid JSON.
   */
  public var MOD_METADATA_PARSE_FAILED:String = 'mod_metadata_parse_failed';

  /**
   * The mod's version string could not be parsed.
   * - Make sure the metadata JSON contains a valid Semantic Version string.
   */
  public var MOD_VERSION_PARSE_FAILED:String = 'mod_version_parse_failed';

  /**
   * The mod's API version string could not be parsed.
   * - Make sure the metadata JSON contains a valid Semantic Version string.
   */
  public var MOD_API_VERSION_PARSE_FAILED:String = 'mod_api_version_parse_failed';

  /**
   * A mod with the given ID is missing an icon file.
   * - This is a warning and can be ignored. Polymod will still load your mod, but it looks better if you add an icon.
   * - The default location for icons is `_polymod_icon.png`.
   */
  public var MOD_MISSING_ICON:String = 'mod_missing_icon';

  //
  // Mod Loading Errors
  //

  /**
   * Polymod is preparing to load a particular mod.
   * - This is an info message. You can log it or ignore it if you like.
   */
  public var MOD_LOAD_START:String = 'mod_load_start';

  /**
   * Polymod attempted to load a particular mod, but failed.
   * - There will generally be another warning or error before this indicating the reason for the error.
   */
  public var MOD_LOAD_FAILED:String = 'mod_load_failed';

  /**
   * Polymod has successfully loaded a particular mod.
   * - This is an info message. You can log it or ignore it if you like.
   * - This is also a good trigger for a UI indicator like a toast notification.
   */
  public var MOD_LOAD_DONE:String = 'mod_load_done';

  //
  // Mod Dependency Errors
  //

  /**
   * Polymod attempted to load a mod, but one or more of its dependencies were missing.
   * - This is a warning if `skipDependencyErrors` is true, the problematic mod will be skipped.
   * - This is an error if `skipDependencyErrors` is false, no mods will be loaded.
   * - Make sure to inform the user that the optional mods are missing.
   */
  public var MOD_OPTIONAL_DEPENDENCY_UNMET:String = 'mod_optional_dependency_unmet';

  /**
   * Polymod attempted to load a mod, but one or more of its dependencies were missing.
   * - This is a warning if `skipDependencyErrors` is true, the problematic mod will be skipped.
   * - This is an error if `skipDependencyErrors` is false, no mods will be loaded.
   * - Make sure to inform the user that the required mods are missing.
   */
  public var MOD_DEPENDENCY_UNMET:String = 'mod_dependency_unmet';

  /**
   * Polymod attempted to load a mod, and its dependency was found,
   * but the version number of the dependency did not match that required by the mod.
   * - This is a warning if `skipDependencyErrors` is true, the problematic mod will be skipped.
   * - This is an error if `skipDependencyErrors` is false, no mods will be loaded.
   * - Make sure to inform the user that the required mods have a mismatched version.
   */
  public var MOD_DEPENDENCY_VERSION_MISMATCH:String = 'mod_dependency_version_mismatch';

  /**
   * Polymod attempted to load a mod, but one of its dependencies created a loop.
   * For example, Mod A requires Mod B, which requires Mod C, which requires Mod A.
   * - This is a warning if `skipDependencyErrors` is true, the problematic mods will be skipped.
   * - This is an error if `skipDependencyErrors` is false, no mods will be loaded.
   * - Inform the mod authors that the dependency issue exists and must be resolved.
   */
  public var MOD_DEPENDENCY_CYCLICAL:String = 'mod_dependency_cyclical';

  /**
   * Polymod was configured to skip dependency checks when loading mods, and that mod order should not be checked.
   * - Make sure you are certain this behavior is correct and that you have properly configured Polymod.
   * - This is a warning and can be ignored.
   */
  public var MOD_DEPENDENCY_CHECK_SKIPPED:String = 'dependency_check_skipped';

  //
  // Mod Compatibility Errors
  //

  /**
   * The given mod's API version does not match the version rule passed to Polymod.init.
   * - This generally indicates the mod is outdated and should be updated by the author.
   * - Depending on the changes made between API versions, it may be that the only necessary change is editing the version string in the metadata file.
   */
  public var MOD_API_VERSION_MISMATCH:String = 'mod_api_version_mismatch';

  //
  // Polymod App Configuration Errors
  //

  /**
   * The app's API version string (passed to Polymod.init) could not be parsed.
   * - Make sure the string is a valid Semantic Version string.
   */
  public var APP_API_VERSION_PARSE_FAILED:String = 'app_api_version_parse_failed';

  /**
   * A bad `customFilesystem` argument was passed to `Polymod.init()`.
   * - Ensure the input is either an `IFileSystem` or a `Class<IFileSystem>`.
   */
  public var APP_BAD_CUSTOM_FILESYSTEM:String = 'app_bad_custom_filesystem';

  //
  // Polymod Framework and Backend Errors
  //

  /**
   * Indicates what asset framework Polymod has been automatically or manually configured to use.
   * - This is an info message, and can either be logged or ignored.
   */
  public var FRAMEWORK_INIT:String = 'framework_init';

  /**
   * You configured Polymod to use the `CUSTOM` asset framework, then didn't provide a custom backend to Polymod.
   * - Ensure that `params.customBackend` provides a `Class<IBackend>`.
   */
  public var BACKEND_CUSTOM_UNDEFINED:String = 'backend_custom_undefined';

  /**
   * Polymod could not create the provided backend for the detected framework.
   * - Read the error message for more information.
   * - For the `CUSTOM` backend, ensure that `params.customBackend` provides a `Class<IBackend>` that can be properly instantiated.
   */
  public var BACKEND_INIT_FAILED:String = 'backend_init_failed';

  /**
   * Polymod has successfully registered a core asset path redirect.
   * All standard assets will be loaded from the target directory instead of the original `assets` folder.
   */
  public var ASSET_REDIRECT_DONE:String = 'asset_redirect_init_done';

  /**
   * Polymod has failed to register a core asset path redirect.
   * - Read the error message for more information.
   */
  public var ASSET_REDIRECT_MISSING_DIRECTORY:String = 'asset_redirect_missing_directory';

  /**
   * Polymod has failed to register a core asset path redirect.
   * - Read the error message for more information.
   */
  public var ASSET_REDIRECT_FAILED:String = 'asset_redirect_failed';

  /**
   * Could not initialize the provided file system.
   */
  public var FILESYSTEM_INIT_FAILED:String = 'filesystem_init_failed';

  //
  // Backend-Specific Errors: Lime
  //

  /**
   * On the Lime and OpenFL platforms, if the base app defines multiple asset libraries,
   * each asset library must be assigned a path to allow mods to override their files.
   * - Provide a `frameworkParams.assetLibraryPaths` object to Polymod.init().
   */
  public var BACKEND_LIME_MISSING_ASSET_LIBRARY_INFO = 'backend_lime_missing_asset_library_info';

  /**
   * On the Lime and OpenFL platforms, if the base app defines multiple asset libraries,
   * each asset library must be assigned a path to allow mods to override their files.
   * - All libraries must have a value under `frameworkParams.assetLibraryPaths`.
   * - Set the value to `./` to fetch assets from the root of the mod folder.
   */
  public var BACKEND_LIME_MISSING_ASSET_LIBRARY_REFERENCE = 'backend_lime_missing_asset_library_reference';

  //
  // Asset Access Errors
  //

  /**
   * Polymod tried to access a file from its filesystem, but that file could not be retrieved because it was missing.
   * - Make sure the file exists before attempting to access it.
   */
  public var ASSET_MISSING_FILE:String = 'asset_missing_file';

  /**
   * Polymod tried to access a directory that was not found.
   * - Make sure the directory exists before attempting to access it.
   */
  public var ASSET_MISSING_DIRECTORY:String = 'asset_missing_directory';

  /**
   * There was a warning or error attempting to perform a merge operation on a file.
   * - Check the source and target files are correctly formatted and try again.
   */
  public var ASSET_MERGE_FAILED:String = 'asset_merge_failed';

  /**
   * There was a warning or error attempting to perform an append operation on a file.
   * - Check the source and target files are correctly formatted and try again.
   */
  public var ASSET_APPEND_FAILED:String = 'asset_append_failed';

  //
  // Script Parsing Errors
  //

  /**
   * One or more scripts are about to be parsed.
   * - This is an info message. You can log it or ignore it if you like.
   */
  public var SCRIPT_PARSE_START:String = 'script_parse_start';

  /**
   * One or more scripts have been successfully parsed.
   * - This is an info message. You can log it or ignore it if you like.
   */
  public var SCRIPT_PARSE_DONE:String = 'script_parse_done';

  /**
   * A script file could not be parsed for some unknown reason.
   * - Check the syntax of the script file is proper Haxe code.
   * - Read the error message for more information.
   */
  public var SCRIPT_PARSE_FAILED:String = 'script_parse_failed';

  //
  // Script Execution Errors
  //

  /**
   * While running a script, an exception was thrown.
   * - Read the error message for more information.
   * - Annotated functions will have the local variable `script_error` assigned, allowing you to handle the error gracefully.
   * - Scripted classes will purge the offending function, preventing the error from occurring again until the script is reloaded.
   */
  public var SCRIPT_RUNTIME_EXCEPTION:String = 'script_runtime_exception';

  //
  // Scripted Function Loading Errors
  //

  /**
   * Polymod attempted to load a specific script file, but could not find it.
   * - This happens when calling annotated functions in an `HScriptable` class when no script file exists.
   * - Make sure the script file exists in the proper location in your assets folder.
   * - Alternatively, you can expand your annotation to `@:hscript({optional: true})` to disable the error message,
   *     if your function can resolve properly without an attached script.
   */
  public var SCRIPT_NOT_FOUND:String = 'script_not_found';

  /**
   * The scripted class does not import an `Assets` class to handle script loading.
   * - When using `HScriptable` to invoke scripts with annotated functions, `Assets.getText` will be used to load the relevant script.
   * - You will need to import `openfl.util.Assets` on the HScriptable class, even if you don't otherwise use it.
   */
  public var SCRIPT_NO_ASSET_HANDLER:String = 'script_no_asset_handler';

  //
  // Scripted Class Loading Errors
  //

  /**
   * You attempted to instantiate a scripted class when no scripted classes were initialized.
   * - Make sure that `useScriptedClasses` in your Polymod.init parameters is set to true.
   */
  public var SCRIPTED_CLASS_NOT_INITIALIZED:String = 'scripted_class_not_initialized';

  /**
   * You attempted to instantiate a scripted class that was not registered.
   * - Make sure the script file containing your scripted class is in the assets folder.
   * - Make sure that `useScriptedClasses` in your Polymod.init parameters is set to true.
   * - If your scripted class extends another class, make sure that class exists as well.
   */
  public var SCRIPTED_CLASS_NOT_REGISTERED:String = 'scripted_class_not_registered';

  /**
   * You attempted to register a new scripted class or enum with a name that is already in use.
   * - Rename the scripted class to one that is unique and will not conflict with other scripted classes.
   * - You can also use a package name to avoid conflicts, although you may have to refer to the class by its full name to use it.
   * - If you need to clear all existing class descriptors, call `Polymod.clearScripts()`.
   */
  public var SCRIPTED_CLASS_ALREADY_REGISTERED:String = 'scripted_class_already_registered';

  /**
   * Your script file attempted to import a class or module that was already imported.
   * - This is a warning and can be ignored.
   * - Remove the duplicate import statement to resolve the warning.
   */
  public var SCRIPTED_CLASS_REDUNDANT_IMPORT:String = 'scripted_class_redundant_import';

  /**
   * Your script file attempted to import a class or module that could not be resolved.
   * - Check the syntax of the import statement, and check for any typos.
   */
  public var SCRIPTED_CLASS_UNRESOLVED_IMPORT:String = 'scripted_class_unresolved_import';

  //
  // Scripted Class Runtime Errors
  //

  /**
   * Your script file attempted to import a class that was blacklisted with `Polymod.blacklistImport()`.
   * - This is a security measure to prevent malicious scripts from accessing sensitive classes.
   * - Remove the import statement to remove the error.
   */
  public var SCRIPTED_CLASS_BLACKLISTED_MODULE:String = 'scripted_class_blacklisted_module';

  /**
   * Your script file attempted to access a field that was blacklisted with `Polymod.blacklistStaticFields()` or `Polymod.blacklistInstanceFields()`
   * - This is a security measure to prevent malicious scripts from accessing sensitive fields.
   * - Remove the field access to remove the error.
   */
  public var SCRIPTED_CLASS_BLACKLISTED_FIELD:String = 'scripted_class_blacklisted_field';
}
